---
repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.3
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=auto
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-yaml
        args:
          - --unsafe
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.14.0a0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
exclude: ^(roles|collections|module_utils|plugins)/.*$
