---
- name: Copy powerbackup script
  ansible.builtin.copy:
    src: powerbackup
    dest: /usr/local/sbin/powerbackup
    mode: "0755"
    owner: root
    group: root

- name: Copy powerbackup_rotate script
  ansible.builtin.copy:
    src: powerbackup_rotate
    dest: /usr/local/sbin/powerbackup_rotate
    mode: "0755"
    owner: root
    group: root

- name: Create powerbackup_rotate.sh wrapper
  ansible.builtin.template:
    src: powerbackup_rotate.sh.j2
    dest: /opt/powerbackup_rotate.sh
    mode: "0755"
    owner: root
    group: root

- name: Create config directory
  ansible.builtin.file:
    path: /etc/powerbackup
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Create tasks directorys
  ansible.builtin.file:
    path: "/etc/powerbackup/{{ item.name }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  with_items: "{{ powerbackup_tasks }}"

- name: Create tasks include file
  ansible.builtin.template:
    src: "include.j2"
    dest: "/etc/powerbackup/{{ item.name }}/include"
    mode: "0644"
    owner: root
    group: root
  with_items: "{{ powerbackup_tasks }}"

- name: Create tasks exclude file
  ansible.builtin.template:
    src: "exclude.j2"
    dest: "/etc/powerbackup/{{ item.name }}/exclude"
    mode: "0644"
    owner: root
    group: root
  with_items: "{{ powerbackup_tasks }}"
  when:
    - item.exclude_dir is defined
    - item.exclude_dir | length > 0

- name: Creates powerbackup rotate cronjob
  ansible.builtin.cron:
    minute: "5"
    hour: "0"
    name: "Rotate backup files"
    job: "/opt/powerbackup_rotate.sh 2>&1 | tee -a {{ powerbackup_destination_dir }}/backup_rotate.log"

- name: Creates powerbackup cronjob
  ansible.builtin.cron:
    minute: "5"
    hour: "1"
    name: "Backup files"
    job: "cd {{ powerbackup_destination_dir }} && /usr/local/sbin/powerbackup 2>&1 | tee -a {{ powerbackup_destination_dir }}/backup.log"

- name: Creates powerbackup cronjob for full backup
  ansible.builtin.cron:
    special_time: "{{ powerbackup_fullbackup_periodically | default('weekly') }}"
    name: "Next run powerbackup create full backup"
    job: "find {{ powerbackup_destination_dir }} -name *.snap -delete"

- name: Create backup destination directory
  ansible.builtin.file:
    path: "{{ powerbackup_destination_dir }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
